### ISSUE TITLE
Server tags are not very good

### ISSUE THREAD

**Issue by cmdwm** [discordextremelist/website#98]
### Feature request

**Is your feature request related to a problem? Please describe.**
Nope, the issue is the current server tags don't appeal to many people.

**Describe the solution you'd like**
I would like to see more tags such as "Giveaways", "General Chat", "Epic Bots", "Coding", etc.

**Describe alternatives you've considered**
No alternatives at the moment, just change the dogshit tags thanks

**Additional context**
what

### Todo
*Added by @Cairo2k18*

- [ ] Rename `Server Tags` to `Server Topics`
- [ ] Add the ability for servers to add custom tags (up to 5)
- [ ] Add topic pages (like with bot tag pages, only show bots in that topic)
- [ ] Add custom tag pages (like with bot tag pages, show bots with that tag ONLY)

**Comment by Cairo2k18** [comment]
The only decent tag suggestion is Coding and even that's covered by the broad term: 
> Science & Tech

**Comment by Cairo2k18** [comment]
blame discord

**Comment by whasonyt** [comment]
or.. instead of using all of discord's discovery tags, just use the good ones? it's not too hard to change them lol

**Comment by carolinaisslaying** [comment]
I think the current tags are sufficient.
